apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: the-forum
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '20'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 404939446326-compute@developer.gserviceaccount.com
      containers:
      - image: gcr.io/vertex-ai-middleware-prod/the-forum:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: GCP_PROJECT_ID
          value: vertex-ai-middleware-prod
        - name: ENVIRONMENT
          value: production
        - name: GCP_LOCATION
          value: us-central1
        - name: GCS_BUCKET_NAME
          value: vertex-ai-middleware-prod-slack-files
        - name: SLACK_SIGNING_SECRET
          valueFrom:
            secretKeyRef:
              name: slack-signing-secret
              key: latest
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
        startupProbe:
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
